services:
  it-tools:
    image: 'corentinth/it-tools:latest'
    deploy:
      resources:
        limits:
          cpus: ${CPU}
          memory: ${MEMORY}
    networks:
      - private
    restart: unless-stopped
    container_name: it-tools

# Networks public / private if not attached to host
networks:
  private:
    name: ${APP_NAME}-private
    internal: true
