services:
  handbrake:
    image: jlesage/handbrake
    container_name: handbrake
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "5"
    hostname: handbrake
    environment:
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
      - TZ=${TZ}
      - DARK_MODE=${DARK_MODE}
      - DISPLAY_WIDTH=${DISPLAY_WIDTH}
      - DISPLAY_HEIGHT=${DISPLAY_HEIGHT}
      - AUTOMATED_CONVERSION_MAX_WATCH_FOLDERS=${AUTOMATED_CONVERSION_MAX_WATCH_FOLDERS}
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR=SAME_AS_SRC
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR_2=SAME_AS_SRC
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR_3=SAME_AS_SRC
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR_4=SAME_AS_SRC
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR_5=SAME_AS_SRC
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR_6=SAME_AS_SRC
      - AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS=${AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS}
      - AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS_2=${AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS}
      - AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS_3=${AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS}
      - AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS_4=${AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS}
      - AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS_5=${AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS}
      - AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS_6=${AUTOMATED_CONVERSION_HANDBRAKE_CUSTOM_ARGS}
      - AUTOMATED_CONVERSION_OUTPUT_DIR=/output
      - AUTOMATED_CONVERSION_OUTPUT_DIR_2=/output2
      - AUTOMATED_CONVERSION_OUTPUT_DIR_3=/output3
      - AUTOMATED_CONVERSION_OUTPUT_DIR_4=/output4
      - AUTOMATED_CONVERSION_OUTPUT_DIR_5=/output3
      - AUTOMATED_CONVERSION_OUTPUT_DIR_6=/output
      - AUTOMATED_CONVERSION_PRESET=${AUTOMATED_CONVERSION_PRESET}
      - AUTOMATED_CONVERSION_PRESET_2=${AUTOMATED_CONVERSION_PRESET}
      - AUTOMATED_CONVERSION_PRESET_3=${AUTOMATED_CONVERSION_PRESET}
      - AUTOMATED_CONVERSION_PRESET_4=${AUTOMATED_CONVERSION_PRESET}
      - AUTOMATED_CONVERSION_PRESET_5=${AUTOMATED_CONVERSION_PRESET_ANIMATION}
      - AUTOMATED_CONVERSION_PRESET_6=${AUTOMATED_CONVERSION_PRESET_ANIMATION}
      - AUTOMATED_CONVERSION_KEEP_SOURCE=0   # 0 = no 1 = yes
      - AUTOMATED_CONVERSION_KEEP_SOURCE_2=0 # 0 = no 1 = yes
      - AUTOMATED_CONVERSION_KEEP_SOURCE_3=0 # 0 = no 1 = yes
      - AUTOMATED_CONVERSION_KEEP_SOURCE_4=0 # 0 = no 1 = yes
      - AUTOMATED_CONVERSION_KEEP_SOURCE_5=0 # 0 = no 1 = yes
      - AUTOMATED_CONVERSION_KEEP_SOURCE_6=0 # 0 = no 1 = yes
      - AUTOMATED_CONVERSION_FORMAT=${AUTOMATED_CONVERSION_FORMAT}
      - AUTOMATED_CONVERSION_FORMAT_2=${AUTOMATED_CONVERSION_FORMAT}
      - AUTOMATED_CONVERSION_FORMAT_3=${AUTOMATED_CONVERSION_FORMAT}
      - AUTOMATED_CONVERSION_FORMAT_4=${AUTOMATED_CONVERSION_FORMAT}
      - AUTOMATED_CONVERSION_FORMAT_5=${AUTOMATED_CONVERSION_FORMAT}
      - AUTOMATED_CONVERSION_FORMAT_6=${AUTOMATED_CONVERSION_FORMAT}
      - INSTALL_PACKAGES=${INSTALL_PACKAGES}
      - HANDBRAKE_GUI=${HANDBRAKE_GUI}
      # Script Environments
      - API_KEY=${API_KEY}
      - PLEX_URL=${PLEX_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - net
    ports:
      - 5800:5800/tcp
    volumes:
      # handbrake paths
      - ./config:/config:rw
      - ./:/storage:rw
      - ./handbrake/Movies:/watch:rw
      - ./handbrake/Movies_NSFW:/watch2:rw
      - ./handbrake/TV Shows/:/watch3:rw
      - ./handbrake/TV Shows_NSFW/:/watch4:rw
      - ./handbrake/Anime_Series/:/watch5:rw
      - ./handbrake/Anime_Movies/:/watch6:rw
      - ./media/Movies:/output:rw
      - ./media/Movies_NSFW:/output2:rw
      - ./media/TV Shows/:/output3:rw
      - ./media/TV Shows_NSFW/:/output4:rw

networks:
  net:
    name: handbrake-net
    enable_ipv6: false
    # set the below to true after container creation need to install some packages for certain automation to work
    internal: true
