services:
  pbs-client:
    image: aterfax/pbs-client
    container_name: proxmox-backup-client
    hostname: ${PROXMOX_CLIENT_NAME}
    labels:
      - com.centurylinklabs.watchtower.enable=false
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UNENCRYPTED=${UNENCRYPTED}
      - PBS_ENDPOINT=${PBS_ENDPOINT}
      - PBS_DATASTORE=${PBS_DATASTORE}
      - CRON_SCHEDULE=${CRON_SCHEDULE}
      - CRON_BACKUP_ONLY=${CRON_BACKUP_ONLY}
      - PBS_API_KEY_NAME=${PBS_API_KEY_NAME}
      - PBS_API_KEY_SECRET=${PBS_API_KEY_SECRET}
    dns:
      - 10.0.53.10
      - 10.0.53.20
    networks:
      - pbs-network
    tmpfs:
      - /tmp
      - /run:exec
    volumes:
      # Timezone
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Backup Config
      - ./:/backups/yourbackupfolder:ro # make sure its READ ONLY
      # exclude subdir in yourbackupfolder
      - /backups/yourbackupfolder/subfolder
      # exclude subfile in yourbackupfolder
      - /dev/null:/backups/yourbackupfolder/subfolder/file.txt
    restart: unless-stopped
