services:
  pbs-client:
    image: aterfax/pbs-client
    container_name: proxmox-backup-client
    hostname: dns-server1
    labels:
      - com.centurylinklabs.watchtower.enable=false
    depends_on:
      - adguardhome
    environment:
      - UNENCRYPTED=${UNENCRYPTED}
      - PBS_ENDPOINT=${PBS_ENDPOINT}
      - PBS_DATASTORE=${PBS_DATASTORE}
      - CRON_SCHEDULE=${CRON_SCHEDULE}
      - CRON_BACKUP_ONLY=${CRON_BACKUP_ONLY}
      - PBS_API_KEY_NAME=${PBS_API_KEY_NAME}
      - PBS_API_KEY_SECRET=${PBS_API_KEY_SECRET}
    dns:
      - 10.0.53.10
      - 10.0.53.20
    networks:
      - pbs-network
    tmpfs:
      - /tmp
      - /run:exec
    volumes:
      - ./:/backups/yourbackupfolder:ro # make sure its READ ONLY
    restart: unless-stopped
