services:
  unbound:
    container_name: unbound
    image: madnuttah/unbound:latest
    hostname: unbound
    networks:
      dns-network:
        ipv4_address: 172.30.0.2
    environment:
      - TZ=${TZ}
      - UNBOUND_UID=${PUID}
      - UNBOUND_GID=${PGID}
      - HEALTHCHECK_PORT=${HEALTHCHECK_PORT}
      - EXTENDED_HEALTHCHECK=${EXTENDED_HEALTHCHECK}
      - EXTENDED_HEALTHCHECK_DOMAIN=${EXTENDED_HEALTHCHECK_DOMAIN}
      - DISABLE_SET_PERMS=${DISABLE_SET_PERMS}
    labels:
      - com.centurylinklabs.watchtower.enable=false
    volumes:
      - ./unbound.conf:/usr/local/unbound/unbound.conf:rw
      - ./log.d/unbound.log:/usr/local/unbound/log.d/unbound.log:rw
    restart: unless-stopped
    healthcheck:
      test: /usr/local/unbound/sbin/healthcheck.sh
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 30s

networks:
  dns-network:
    driver: bridge
    name: dns-network
    external: false
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1