services:
  # Ref Doc: https://github.com/AdguardTeam/AdGuardHome
  adguardhome:
    image: adguard/adguardhome
    network_mode: host
    container_name: adguardhome
    volumes:
      - ./app-config/work:/opt/adguardhome/work
      - ./app-config/conf:/opt/adguardhome/conf
      - /home/ubuntu/docker/swag/config/etc/letsencrypt/live/${URL}/fullchain.pem:/certs/fullchain.pem:ro
      - /home/ubuntu/docker/swag/config/etc/letsencrypt/live/${URL}/privkey.pem:/certs/privkey.pem:ro
    restart: unless-stopped