services:
  # Ref Doc: https://github.com/AdguardTeam/AdGuardHome
  adguardhome:
    image: adguard/adguardhome
    network_mode: host
    container_name: adguardhome
    volumes:
      - ./app-config/work:/opt/adguardhome/work
      - ./app-config/conf:/opt/adguardhome/conf
      - /home/ubuntu/docker/swag/config/etc/letsencrypt/live/${URL}/fullchain.pem:/certs/fullchain.pem:ro
      - /home/ubuntu/docker/swag/config/etc/letsencrypt/live/${URL}/privkey.pem:/certs/privkey.pem:ro
    restart: unless-stopped
  
  # Ref Doc: https://github.com/linuxserver/docker-adguardhome-sync
  adguardhome-sync: # optional for multi-instance adguardhome
    image: lscr.io/linuxserver/adguardhome-sync:latest
    container_name: adguardhome-sync
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - CONFIGFILE=/config/adguardhome-sync.yaml #optional
    volumes:
      - ./sync-config:/config
    restart: unless-stopped
  
